"use client";
import { useMemo, useState } from "react";
import { Download, FileArchive, FileText } from "lucide-react";
import { jsPDF } from "jspdf";
import JSZip from "jszip";
import * as XLSX from "xlsx";
import type { ReportRow } from "@/lib/types";
import { Badge } from "@/components/ui";

export function ReportTable({rows,title,period}:{rows:ReportRow[];title:string;period:string}){
  const classes=useMemo(()=>Array.from(new Set(rows.map(r=>r.className))).sort(),[rows]);const[filter,setFilter]=useState("all");const visible=filter==='all'?rows:rows.filter(r=>r.className===filter);
  const makePdf=(r:ReportRow)=>{const doc=new jsPDF();doc.setFont('helvetica','bold');doc.setFontSize(18);doc.text(title,20,20);doc.setFontSize(11);doc.setFont('helvetica','normal');doc.text(`Nama: ${r.studentName}`,20,32);doc.text(`Kelas: ${r.className}`,20,39);doc.text(`Periode: ${period}`,20,46);doc.setDrawColor(220);doc.line(20,52,190,52);doc.setFont('helvetica','bold');doc.text('Ringkasan',20,62);doc.setFont('helvetica','normal');doc.text(`Kehadiran: ${r.attendanceRate}% (${r.present}/${r.meetings})`,20,71);doc.text(`Setoran: ${r.submissions} | Hafalan baru: ${r.newMemorization} | Murajaah: ${r.murajaah}`,20,78);doc.text(`Kelancaran: ${r.fluency.toFixed(1)} | Tajwid: ${r.tajwid.toFixed(1)} | Makhraj: ${r.makhraj.toFixed(1)}`,20,85);doc.text(`Progress target: ${r.progressPercent}%`,20,92);doc.setFont('helvetica','bold');doc.text('Analisis Perkembangan',20,105);doc.setFont('helvetica','normal');doc.text(doc.splitTextToSize(r.analysis,170),20,113);doc.setFont('helvetica','bold');doc.text('Narasi Perkembangan',20,145);doc.setFont('helvetica','normal');doc.text(doc.splitTextToSize(r.narrative,170),20,153);doc.setFont('helvetica','bold');doc.text('Fokus Pembinaan Berikutnya',20,183);doc.setFont('helvetica','normal');doc.text(doc.splitTextToSize(r.nextFocus,170),20,191);if(r.reportNotes.length){doc.setFont('helvetica','bold');doc.text('Catatan Guru',20,220);doc.setFont('helvetica','normal');doc.text(doc.splitTextToSize(r.reportNotes.join(' • '),170),20,228);}return doc;};
  const pdf=(r:ReportRow)=>makePdf(r).save(`${safe(r.studentName)}_${safe(period)}.pdf`);
  const excel=()=>{const wb=XLSX.utils.book_new();const summary=visible.map((r,i)=>({No:i+1,Nama:r.studentName,Kelas:r.className,Kehadiran:`${r.attendanceRate}%`,Setoran:r.submissions,'Hafalan Baru':r.newMemorization,Murajaah:r.murajaah,Kelancaran:+r.fluency.toFixed(2),Tajwid:+r.tajwid.toFixed(2),Makhraj:+r.makhraj.toFixed(2),'Nilai Rata-rata':+r.averageScore.toFixed(2),'Progress Target':`${r.progressPercent}%`,'Fokus Pembinaan':r.nextFocus}));XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(summary),'Ringkasan');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(visible.map(r=>({Nama:r.studentName,Kelas:r.className,Analisis:r.analysis,Narasi:r.narrative,Catatan:r.reportNotes.join(' | '),Rekomendasi:r.nextFocus}))),'Narasi & Analisis');XLSX.writeFile(wb,`Rekap_Tahfidz_${safe(period)}_${filter==='all'?'Semua_Kelas':filter}.xlsx`);};
  const allPdf=async()=>{const zip=new JSZip();visible.forEach(r=>zip.file(`${safe(r.studentName)}.pdf`,makePdf(r).output('arraybuffer')));const blob=await zip.generateAsync({type:'blob'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`Laporan_PDF_${safe(period)}_${filter}.zip`;a.click();URL.revokeObjectURL(a.href);};
  return <div className="space-y-4"><div className="flex flex-wrap gap-2"><select className="input w-auto min-w-40" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Semua kelas</option>{classes.map(c=><option key={c} value={c}>Kelas {c}</option>)}</select><div className="ml-auto flex flex-wrap gap-2"><button onClick={allPdf} className="button-secondary"><FileArchive size={16}/> Semua PDF</button><button onClick={excel} className="button-primary"><Download size={16}/> Excel Kelas</button></div></div><div className="card overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-left text-sm"><thead className="bg-slate-50 text-[10px] uppercase tracking-wide text-muted"><tr>{['Siswa','Kelas','Hadir','Setoran','Hafalan','Murajaah','Nilai','Progress','Laporan'].map(h=><th key={h} className="px-4 py-3 font-bold">{h}</th>)}</tr></thead><tbody className="divide-y divide-line">{visible.map(r=><tr key={r.studentId} className="hover:bg-teal-50/30"><td className="px-4 py-4 font-bold">{r.studentName}</td><td className="px-4 py-4"><Badge>{r.className}</Badge></td><td className="px-4 py-4">{r.attendanceRate}%</td><td className="px-4 py-4">{r.submissions}</td><td className="px-4 py-4">{r.newMemorization}</td><td className="px-4 py-4">{r.murajaah}</td><td className="px-4 py-4 font-bold">{r.averageScore.toFixed(1)}</td><td className="px-4 py-4">{r.progressPercent}%</td><td className="px-4 py-4"><button onClick={()=>pdf(r)} className="inline-flex items-center gap-1.5 rounded-lg bg-teal-50 px-3 py-2 text-xs font-bold text-teal-800"><FileText size={14}/> PDF</button></td></tr>)}</tbody></table></div></div></div>;
}
function safe(s:string){return s.replace(/[^a-zA-Z0-9_-]+/g,'_')}
