"use client";
import { useState, useTransition } from "react";
import { Loader2, Plus } from "lucide-react";
import { createStudentNoteAction, createFocusAction } from "@/app/actions";
import { format } from "date-fns";

export function StudentNoteForm({studentId}:{studentId:string}){const[pending,startTransition]=useTransition();const[msg,setMsg]=useState("");const submit=(fd:FormData)=>startTransition(async()=>{const res=await createStudentNoteAction({studentId,noteDate:String(fd.get('date')),category:String(fd.get('category')),note:String(fd.get('note')),visibility:String(fd.get('visibility')) as any,pinned:fd.get('pinned')==='on'});setMsg(res.ok?'Catatan tersimpan.':res.message??'Gagal menyimpan');});return <form action={submit} className="card p-5"><div className="flex items-center gap-2"><Plus size={17} className="text-teal-700"/><h3 className="font-extrabold">Tambah Catatan</h3></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><div><label className="mb-1.5 block text-xs font-bold">Tanggal</label><input name="date" type="date" defaultValue={format(new Date(),"yyyy-MM-dd")} className="input"/></div><div><label className="mb-1.5 block text-xs font-bold">Kategori</label><select name="category" className="input"><option>Hafalan</option><option>Murajaah</option><option>Tajwid</option><option>Makhraj</option><option>Kelancaran</option><option>Kedisiplinan</option><option>Motivasi</option><option>Perkembangan Umum</option></select></div><div className="sm:col-span-2"><label className="mb-1.5 block text-xs font-bold">Catatan</label><textarea required name="note" className="textarea" placeholder="Tuliskan perkembangan, kendala, atau hal penting yang ingin diingat..."/></div><div><label className="mb-1.5 block text-xs font-bold">Penggunaan catatan</label><select name="visibility" className="input"><option value="internal">Internal Guru 🔒</option><option value="report">Boleh Masuk Laporan 📄</option></select></div><label className="flex items-center gap-2 self-end rounded-xl bg-amber-50 p-3 text-xs font-semibold text-amber-800"><input name="pinned" type="checkbox"/> Pin sebagai catatan penting</label></div>{msg&&<p className="mt-3 text-xs font-semibold text-teal-700">{msg}</p>}<button disabled={pending} className="button-primary mt-4">{pending?<Loader2 className="animate-spin" size={16}/>:<Plus size={16}/>} Simpan Catatan</button></form>}

export function FocusForm({studentId}:{studentId:string}){const[pending,startTransition]=useTransition();const[msg,setMsg]=useState("");return <form action={(fd)=>startTransition(async()=>{const res=await createFocusAction({studentId,title:String(fd.get('title'))});setMsg(res.ok?'Fokus pembinaan ditambahkan.':res.message??'Gagal');})} className="flex gap-2"><input name="title" required className="input" placeholder="Contoh: Makhraj huruf ض"/><button disabled={pending} className="button-primary shrink-0">Tambah</button>{msg&&<span className="sr-only">{msg}</span>}</form>}
