"use client";
import { useMemo, useState, useTransition } from "react";
import { BookOpenCheck, CheckCircle2, Loader2, Plus, X } from "lucide-react";
import { createSubmissionAction } from "@/app/actions";
import { QURAN_SURAHS } from "@/lib/surahs";
import { Badge } from "@/components/ui";
import { cn } from "@/lib/utils";

export type QueueRow={id:string;full_name:string;class_name:string;present:boolean;submitted:boolean;lastMemorization:string;focus?:string|null};
export function SubmissionBoard({rows,date,mode="hafalan_baru"}:{rows:QueueRow[];date:string;mode?:"hafalan_baru"|"murajaah"}){
  const [tab,setTab]=useState<"pending"|"done"|"all">(mode==="murajaah"?"all":"pending");const [selected,setSelected]=useState<QueueRow|null>(null);const [filter,setFilter]=useState("all");
  const classes=useMemo(()=>Array.from(new Set(rows.map(r=>r.class_name))).sort(),[rows]);
  const visible=rows.filter(r=>(filter==="all"||r.class_name===filter)&&(mode==="murajaah"||tab==="all"||(tab==="pending"?!r.submitted:r.submitted))&&(mode==="murajaah"||r.present));
  return <div className="space-y-4"><div className="flex flex-wrap gap-2"><div className="flex rounded-xl border border-line bg-white p-1">{mode!=="murajaah"&&([['pending','Belum Setor'],['done','Sudah Setor'],['all','Semua']] as const).map(([k,l])=><button key={k} onClick={()=>setTab(k)} className={cn("rounded-lg px-3 py-2 text-xs font-bold",tab===k?"bg-teal-700 text-white":"text-muted")}>{l}</button>)}</div><select value={filter} onChange={e=>setFilter(e.target.value)} className="input ml-auto w-auto min-w-36"><option value="all">Semua kelas</option>{classes.map(c=><option key={c} value={c}>Kelas {c}</option>)}</select></div>
    <div className="grid gap-4 lg:grid-cols-2">{visible.map(r=><div key={r.id} className="card p-5"><div className="flex items-start gap-3"><div className="grid h-11 w-11 shrink-0 place-items-center rounded-2xl bg-teal-50 text-sm font-extrabold text-teal-800">{r.full_name[0]}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="font-extrabold">{r.full_name}</h3><Badge>Kelas {r.class_name}</Badge>{r.submitted&&<Badge tone="green">Sudah setor</Badge>}</div><p className="mt-3 text-[11px] font-semibold uppercase tracking-wide text-muted">Terakhir</p><p className="mt-1 text-sm font-semibold">{r.lastMemorization}</p>{r.focus&&<div className="mt-3 rounded-xl bg-amber-50 px-3 py-2 text-xs font-medium text-amber-800">📌 {r.focus}</div>}</div></div><button onClick={()=>setSelected(r)} className="button-primary mt-4 w-full">{r.submitted&&mode!=="murajaah"?<CheckCircle2 size={16}/>:<Plus size={16}/>} {mode==="murajaah"?"Catat Murajaah":"Catat Setoran"}</button></div>)}</div>
    {!visible.length&&<div className="card p-10 text-center"><BookOpenCheck className="mx-auto text-teal-600"/><h3 className="mt-3 font-bold">Tidak ada siswa pada daftar ini</h3><p className="mt-1 text-sm text-muted">Coba ubah filter atau selesaikan absensi terlebih dahulu.</p></div>}
    {selected&&<SubmissionModal student={selected} date={date} defaultType={mode} onClose={()=>setSelected(null)}/>}</div>
}
function SubmissionModal({student,date,defaultType,onClose}:{student:QueueRow;date:string;defaultType:"hafalan_baru"|"murajaah";onClose:()=>void}){
  const [pending,startTransition]=useTransition();const [message,setMessage]=useState("");
  const submit=(fd:FormData)=>startTransition(async()=>{const res=await createSubmissionAction({studentId:student.id,date,type:String(fd.get('type')) as any,surahName:String(fd.get('surah')),startAyah:Number(fd.get('start')),endAyah:Number(fd.get('end')),fluency:Number(fd.get('fluency')),tajwid:Number(fd.get('tajwid')),makhraj:Number(fd.get('makhraj')),mistakes:Number(fd.get('mistakes')),note:String(fd.get('note')||'')});if(res.ok){setMessage("Berhasil disimpan.");setTimeout(()=>onClose(),500)}else setMessage(res.message??"Gagal menyimpan")});
  return <div className="fixed inset-0 z-[80] flex items-end justify-center bg-slate-950/30 p-0 backdrop-blur-sm md:items-center md:p-5"><div className="w-full max-w-xl max-h-[92vh] overflow-y-auto rounded-t-[26px] bg-white p-5 shadow-2xl md:rounded-[26px] md:p-6"><div className="flex items-start justify-between"><div><p className="label">Catat Aktivitas</p><h3 className="mt-1 text-xl font-extrabold">{student.full_name}</h3><p className="text-xs text-muted">Kelas {student.class_name} · terakhir {student.lastMemorization}</p></div><button onClick={onClose} className="grid h-9 w-9 place-items-center rounded-xl bg-slate-100"><X size={17}/></button></div><form action={submit} className="mt-6 grid gap-4 sm:grid-cols-2"><div className="sm:col-span-2"><label className="mb-2 block text-xs font-bold">Jenis</label><select name="type" defaultValue={defaultType} className="input"><option value="hafalan_baru">Hafalan Baru</option><option value="murajaah">Murajaah</option></select></div><div className="sm:col-span-2"><label className="mb-2 block text-xs font-bold">Surah</label><select name="surah" className="input">{QURAN_SURAHS.map(s=><option key={s}>{s}</option>)}</select></div><div><label className="mb-2 block text-xs font-bold">Ayat awal</label><input name="start" type="number" min="1" defaultValue="1" className="input"/></div><div><label className="mb-2 block text-xs font-bold">Ayat akhir</label><input name="end" type="number" min="1" defaultValue="5" className="input"/></div>{[['fluency','Kelancaran'],['tajwid','Tajwid'],['makhraj','Makhraj']] .map(([n,l])=><div key={n}><label className="mb-2 block text-xs font-bold">{l}</label><select name={n} className="input" defaultValue="4"><option value="5">5 · Sangat baik</option><option value="4.5">4.5</option><option value="4">4 · Baik</option><option value="3.5">3.5</option><option value="3">3 · Perlu penguatan</option><option value="2">2</option><option value="1">1</option></select></div>)}<div><label className="mb-2 block text-xs font-bold">Jumlah kesalahan</label><input name="mistakes" type="number" min="0" defaultValue="0" className="input"/></div><div className="sm:col-span-2"><label className="mb-2 block text-xs font-bold">Catatan setoran</label><textarea name="note" className="textarea" placeholder="Contoh: makhraj ض mulai membaik, tetapi mad masih perlu diperhatikan."/></div>{message&&<p className="sm:col-span-2 text-sm font-semibold text-teal-700">{message}</p>}<div className="sm:col-span-2 flex justify-end"><button className="button-primary min-w-40" disabled={pending}>{pending?<Loader2 className="animate-spin" size={16}/>:<BookOpenCheck size={16}/>} Simpan</button></div></form></div></div>
}
