import { notFound } from "next/navigation";
import { Badge, Card } from "@/components/ui";
import { FocusForm, StudentNoteForm } from "@/components/student-note-form";
import { getStudentDetail } from "@/lib/data";
import { format } from "date-fns";
import { id as idLocale } from "date-fns/locale";
import { BookOpen, CalendarCheck2, MessageSquareText, Pin, Sparkles, Target } from "lucide-react";

export const dynamic="force-dynamic";
export default async function StudentDetailPage({params}:{params:Promise<{id:string}>}){const {id}=await params;const data=await getStudentDetail(id);if(!data||!data.student)notFound();const student:any=data.student;const submissions:any[]=data.submissions;const notes:any[]=data.notes;const latest=submissions[0];const scores=submissions.length?submissions.map(x=>(Number(x.fluency_score)+Number(x.tajwid_score)+Number(x.makhraj_score))/3):[];const avg=scores.length?scores.reduce((a,b)=>a+b,0)/scores.length:0;return <div className="mx-auto max-w-7xl space-y-5"><Card className="overflow-hidden border-0 bg-gradient-to-r from-teal-900 to-teal-600 p-6 text-white"><div className="flex flex-col gap-5 sm:flex-row sm:items-center"><div className="grid h-16 w-16 place-items-center rounded-2xl bg-white/15 text-2xl font-extrabold">{student.full_name[0]}</div><div className="flex-1"><p className="text-xs font-semibold text-white/60">PROFIL SISWA</p><h1 className="mt-1 text-2xl font-extrabold">{student.full_name}</h1><p className="mt-1 text-sm text-white/70">Kelas {student.class_name}{student.nis?` · NIS ${student.nis}`:''}</p></div>{data.focus?.filter((f:any)=>f.status==='active').slice(0,2).map((f:any)=><span key={f.id} className="rounded-full bg-white/10 px-3 py-2 text-xs font-bold">📌 {f.title}</span>)}</div></Card>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat icon={BookOpen} label="Setoran tercatat" value={submissions.length}/><Stat icon={Sparkles} label="Nilai rata-rata" value={avg?avg.toFixed(1):'-'}/><Stat icon={CalendarCheck2} label="Hafalan terakhir" value={latest?`${latest.surah_name} ${latest.start_ayah}–${latest.end_ayah}`:'Belum ada'}/><Stat icon={Target} label="Target aktif" value={data.targets?.filter((t:any)=>t.status==='active').length??0}/></section>
    <section className="grid gap-5 xl:grid-cols-[1.15fr_.85fr]"><div className="space-y-5"><Card className="p-5"><div className="flex items-center gap-2"><BookOpen size={17} className="text-teal-700"/><h2 className="font-extrabold">Timeline Setoran</h2></div><div className="mt-4 space-y-3">{submissions.slice(0,10).map((s:any)=><div key={s.id} className="rounded-xl border border-line p-4"><div className="flex flex-wrap items-start justify-between gap-2"><div><div className="font-bold">{s.surah_name} {s.start_ayah}–{s.end_ayah}</div><div className="mt-1 text-xs text-muted">{format(new Date(s.submitted_at),"d MMMM yyyy",{locale:idLocale})} · {s.type==='murajaah'?'Murajaah':'Hafalan Baru'}</div></div><Badge tone={s.type==='murajaah'?'blue':'teal'}>{((Number(s.fluency_score)+Number(s.tajwid_score)+Number(s.makhraj_score))/3).toFixed(1)}</Badge></div>{s.note&&<p className="mt-3 text-xs leading-5 text-muted">{s.note}</p>}</div>)}{!submissions.length&&<p className="py-8 text-center text-sm text-muted">Belum ada setoran.</p>}</div></Card><StudentNoteForm studentId={student.id}/></div>
      <div className="space-y-5"><Card className="p-5"><div className="flex items-center gap-2"><Target size={17} className="text-teal-700"/><h2 className="font-extrabold">Fokus Pembinaan</h2></div><div className="mt-4 space-y-2">{data.focus?.filter((f:any)=>f.status==='active').map((f:any)=><div key={f.id} className="rounded-xl bg-amber-50 p-3 text-xs font-semibold text-amber-800">📌 {f.title}</div>)}{!data.focus?.filter((f:any)=>f.status==='active').length&&<p className="text-xs text-muted">Belum ada fokus aktif.</p>}</div><div className="mt-4"><FocusForm studentId={student.id}/></div></Card><Card className="p-5"><div className="flex items-center gap-2"><MessageSquareText size={17} className="text-teal-700"/><h2 className="font-extrabold">Catatan Saya</h2></div><div className="mt-4 space-y-3">{notes.slice(0,12).map((n:any)=><div key={n.id} className="rounded-xl border border-line p-3"><div className="flex items-center justify-between gap-2"><div className="text-[11px] font-bold text-teal-700">{n.category}</div>{n.pinned&&<Pin size={13} className="text-amber-500"/>}</div><p className="mt-1 text-xs leading-5">{n.note}</p><div className="mt-2 flex items-center gap-2 text-[10px] text-muted"><span>{format(new Date(n.note_date),"d MMM yyyy",{locale:idLocale})}</span><span>•</span><span>{n.visibility==='report'?'Bahan laporan':'Internal guru'}</span></div></div>)}{!notes.length&&<p className="text-xs text-muted">Belum ada catatan tentang siswa ini.</p>}</div></Card></div></section></div>}
function Stat({icon:Icon,label,value}:{icon:any;label:string;value:string|number}){return <Card className="p-4"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-teal-50 text-teal-700"><Icon size={18}/></div><div className="min-w-0"><div className="text-[11px] font-semibold text-muted">{label}</div><div className="mt-1 truncate text-base font-extrabold">{value}</div></div></div></Card>}
